### ISSUE TITLE
No features are being detected by nvim-treesitter

### ISSUE THREAD

**Issue by 0xfadead** [c3lang/tree-sitter-c3#4]
When running `:checkhealth nvim-treesitter` the following output appears:

```
[...]
Parser/Features         H L F I J
[...]
  - c                   ✓ ✓ ✓ ✓ ✓
  - c3                  . . . . .
[...]
```

This means no features are being detected by nvim-treesitter, it can however still communicate the AST to treesitter, as can be seen here:

![image](https://github.com/cbuttner/tree-sitter-c3/assets/69577313/07267c78-e33f-4402-8821-43e34f1f52cd)

**Comment by cbuttner** [comment]
For now you'll have to install `queries/highlights.scm` manually, see: https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#adding-queries
